CALTECH101 = {
    0: 'accordion',
    1: 'airplanes',
    2: 'anchor',
    3: 'ant',
    4: 'background_google',
    5: 'barrel',
    6: 'bass',
    7: 'beaver',
    8: 'binocular',
    9: 'bonsai',
    10: 'brain',
    11: 'brontosaurus',
    12: 'buddha',
    13: 'butterfly',
    14: 'camera',
    15: 'cannon',
    16: 'car_side',
    17: 'ceiling_fan',
    18: 'cellphone',
    19: 'chair',
    20: 'chandelier',
    21: 'cougar_body',
    22: 'cougar_face',
    23: 'crab',
    24: 'crayfish',
    25: 'crocodile',
    26: 'crocodile_head',
    27: 'cup',
    28: 'dalmatian',
    29: 'dollar_bill',
    30: 'dolphin',
    31: 'dragonfly',
    32: 'electric_guitar',
    33: 'elephant',
    34: 'emu',
    35: 'euphonium',
    36: 'ewer',
    37: 'faces',
    38: 'faces_easy',
    39: 'ferry',
    40: 'flamingo',
    41: 'flamingo_head',
    42: 'garfield',
    43: 'gerenuk',
    44: 'gramophone',
    45: 'grand_piano',
    46: 'hawksbill',
    47: 'headphone',
    48: 'hedgehog',
    49: 'helicopter',
    50: 'ibis',
    51: 'inline_skate',
    52: 'joshua_tree',
    53: 'kangaroo',
    54: 'ketch',
    55: 'lamp',
    56: 'laptop',
    57: 'leopards',
    58: 'llama',
    59: 'lobster',
    60: 'lotus',
    61: 'mandolin',
    62: 'mayfly',
    63: 'menorah',
    64: 'metronome',
    65: 'minaret',
    66: 'motorbikes',
    67: 'nautilus',
    68: 'octopus',
    69: 'okapi',
    70: 'pagoda',
    71: 'panda',
    72: 'pigeon',
    73: 'pizza',
    74: 'platypus',
    75: 'pyramid',
    76: 'revolver',
    77: 'rhino',
    78: 'rooster',
    79: 'saxophone',
    80: 'schooner',
    81: 'scissors',
    82: 'scorpion',
    83: 'sea_horse',
    84: 'snoopy',
    85: 'soccer_ball',
    86: 'stapler',
    87: 'starfish',
    88: 'stegosaurus',
    89: 'stop_sign',
    90: 'strawberry',
    91: 'sunflower',
    92: 'tick',
    93: 'trilobite',
    94: 'umbrella',
    95: 'watch',
    96: 'water_lilly',
    97: 'wheelchair',
    98: 'wild_cat',
    99: 'windsor_chair',
    100: 'wrench',
    101: 'yin_yang'
}


CALTECH101_TAXONOMY = {
    "Background": {
        "Background" : {
            "Background": ["background_google"]
        }
    },
    "Living Things": {
        "Animals": {
            "Mammals": ["leopards", "beaver", "cougar_body", "cougar_face", "dalmatian", "dolphin", "elephant", "gerenuk", "hedgehog", "kangaroo", "llama", "okapi", "panda", "platypus", "rhino", "wild_cat"],
            "Birds": ["emu", "flamingo", "flamingo_head", "ibis", "pigeon", "rooster"],
            "Reptiles": ["crocodile", "crocodile_head", "hawksbill"],
            "Insects & Arthropods": ["ant", "butterfly", "crab", "crayfish", "dragonfly", "lobster", "mayfly", "scorpion", "tick"],
            "Marine Animals": ["octopus", "sea_horse", "trilobite", "starfish", "bass", "nautilus"],
            "Dinosaurs": ["brontosaurus", "stegosaurus"],
            "Fictional & Abstract": ["garfield", "buddha"],
        },
        "Plants": {
            "Fruits": ["strawberry"],
            "Trees": ["bonsai", "joshua_tree", "lotus", "sunflower", "water_lilly"]
        },
        "Body Part": {
            "Brain": ["brain"],
            "Face": ["faces", "faces_easy"],

        }

    },
    "Objects": {
        "Architecture": {
            "Architecture": ["minaret", "pagoda", "pyramid"]
        },
        "Vehicles": {
            "Aircraft": ["airplanes", "helicopter"],
            "Watercraft": ["ferry", "ketch", "schooner", "anchor"],
            "Land Vehicles": ["car_side", "motorbikes", "wheelchair", "inline_skate"]
        },
        "Items": {
            "Furniture & Household Items": ["binocular", "camera", "cannon", "chair", "chandelier", "ceiling_fan", "cup", "lamp", "menorah", "metronome", "umbrella", "windsor_chair", "stapler", "ewer"],
            "Electronics": ["cellphone", "headphone", "laptop", "watch"],
            "Tools & Miscellaneous": ["scissors", "wrench", "revolver"],
            "Containers": ["barrel"],
            "Toys & Games": ["soccer_ball", "snoopy"],
            "Food & Edibles": ["pizza"],
            "Musical Instruments": ["accordion", "electric_guitar", "euphonium", "gramophone", "grand_piano", "mandolin", "saxophone"],
        },

        "Symbols & Signs": {
            "Symbols & Signs": ["dollar_bill", "stop_sign", "yin_yang"],
        }
        
    },
    
}
