SUN397 = {
    0: 'abbey',
    1: 'airplane_cabin',
    2: 'airport_terminal',
    3: 'alley',
    4: 'amphitheater',
    5: 'amusement_arcade',
    6: 'amusement_park',
    7: 'anechoic_chamber',
    8: 'apartment_building_outdoor',
    9: 'apse_indoor',
    10: 'aquarium',
    11: 'aqueduct',
    12: 'arch',
    13: 'archive',
    14: 'arrival_gate_outdoor',
    15: 'art_gallery',
    16: 'art_school',
    17: 'art_studio',
    18: 'assembly_line',
    19: 'athletic_field_outdoor',
    20: 'atrium_public',
    21: 'attic',
    22: 'auditorium',
    23: 'auto_factory',
    24: 'badlands',
    25: 'badminton_court_indoor',
    26: 'baggage_claim',
    27: 'bakery_shop',
    28: 'balcony_exterior',
    29: 'balcony_interior',
    30: 'ball_pit',
    31: 'ballroom',
    32: 'bamboo_forest',
    33: 'banquet_hall',
    34: 'bar',
    35: 'barn',
    36: 'barndoor',
    37: 'baseball_field',
    38: 'basement',
    39: 'basilica',
    40: 'basketball_court_outdoor',
    41: 'bathroom',
    42: 'batters_box',
    43: 'bayou',
    44: 'bazaar_indoor',
    45: 'bazaar_outdoor',
    46: 'beach',
    47: 'beauty_salon',
    48: 'bedroom',
    49: 'berth',
    50: 'biology_laboratory',
    51: 'bistro_indoor',
    52: 'boardwalk',
    53: 'boat_deck',
    54: 'boathouse',
    55: 'bookstore',
    56: 'booth_indoor',
    57: 'botanical_garden',
    58: 'bow_window_indoor',
    59: 'bow_window_outdoor',
    60: 'bowling_alley',
    61: 'boxing_ring',
    62: 'brewery_indoor',
    63: 'bridge',
    64: 'building_facade',
    65: 'bullring',
    66: 'burial_chamber',
    67: 'bus_interior',
    68: 'butchers_shop',
    69: 'butte',
    70: 'cabin_outdoor',
    71: 'cafeteria',
    72: 'campsite',
    73: 'campus',
    74: 'canal_natural',
    75: 'canal_urban',
    76: 'candy_store',
    77: 'canyon',
    78: 'car_interior_backseat',
    79: 'car_interior_frontseat',
    80: 'carrousel',
    81: 'casino_indoor',
    82: 'castle',
    83: 'catacomb',
    84: 'cathedral_indoor',
    85: 'cathedral_outdoor',
    86: 'cavern_indoor',
    87: 'cemetery',
    88: 'chalet',
    89: 'cheese_factory',
    90: 'chemistry_lab',
    91: 'chicken_coop_indoor',
    92: 'chicken_coop_outdoor',
    93: 'childs_room',
    94: 'church_indoor',
    95: 'church_outdoor',
    96: 'classroom',
    97: 'clean_room',
    98: 'cliff',
    99: 'cloister_indoor',
    100: 'closet',
    101: 'clothing_store',
    102: 'coast',
    103: 'cockpit',
    104: 'coffee_shop',
    105: 'computer_room',
    106: 'conference_center',
    107: 'conference_room',
    108: 'construction_site',
    109: 'control_room',
    110: 'control_tower_outdoor',
    111: 'corn_field',
    112: 'corral',
    113: 'corridor',
    114: 'cottage_garden',
    115: 'courthouse',
    116: 'courtroom',
    117: 'courtyard',
    118: 'covered_bridge_exterior',
    119: 'creek',
    120: 'crevasse',
    121: 'crosswalk',
    122: 'cubicle_office',
    123: 'dam',
    124: 'delicatessen',
    125: 'dentists_office',
    126: 'desert_sand',
    127: 'desert_vegetation',
    128: 'diner_indoor',
    129: 'diner_outdoor',
    130: 'dinette_home',
    131: 'dinette_vehicle',
    132: 'dining_car',
    133: 'dining_room',
    134: 'discotheque',
    135: 'dock',
    136: 'doorway_outdoor',
    137: 'dorm_room',
    138: 'driveway',
    139: 'driving_range_outdoor',
    140: 'drugstore',
    141: 'electrical_substation',
    142: 'elevator_door',
    143: 'elevator_interior',
    144: 'elevator_shaft',
    145: 'engine_room',
    146: 'escalator_indoor',
    147: 'excavation',
    148: 'factory_indoor',
    149: 'fairway',
    150: 'fastfood_restaurant',
    151: 'field_cultivated',
    152: 'field_wild',
    153: 'fire_escape',
    154: 'fire_station',
    155: 'firing_range_indoor',
    156: 'fishpond',
    157: 'florist_shop_indoor',
    158: 'food_court',
    159: 'forest_broadleaf',
    160: 'forest_needleleaf',
    161: 'forest_path',
    162: 'forest_road',
    163: 'formal_garden',
    164: 'fountain',
    165: 'galley',
    166: 'game_room',
    167: 'garage_indoor',
    168: 'garbage_dump',
    169: 'gas_station',
    170: 'gazebo_exterior',
    171: 'general_store_indoor',
    172: 'general_store_outdoor',
    173: 'gift_shop',
    174: 'golf_course',
    175: 'greenhouse_indoor',
    176: 'greenhouse_outdoor',
    177: 'gymnasium_indoor',
    178: 'hangar_indoor',
    179: 'hangar_outdoor',
    180: 'harbor',
    181: 'hayfield',
    182: 'heliport',
    183: 'herb_garden',
    184: 'highway',
    185: 'hill',
    186: 'home_office',
    187: 'hospital',
    188: 'hospital_room',
    189: 'hot_spring',
    190: 'hot_tub_outdoor',
    191: 'hotel_outdoor',
    192: 'hotel_room',
    193: 'house',
    194: 'hunting_lodge_outdoor',
    195: 'ice_cream_parlor',
    196: 'ice_floe',
    197: 'ice_shelf',
    198: 'ice_skating_rink_indoor',
    199: 'ice_skating_rink_outdoor',
    200: 'iceberg',
    201: 'igloo',
    202: 'industrial_area',
    203: 'inn_outdoor',
    204: 'islet',
    205: 'jacuzzi_indoor',
    206: 'jail_indoor',
    207: 'jail_cell',
    208: 'jewelry_shop',
    209: 'kasbah',
    210: 'kennel_indoor',
    211: 'kennel_outdoor',
    212: 'kindergarden_classroom',
    213: 'kitchen',
    214: 'kitchenette',
    215: 'labyrinth_outdoor',
    216: 'lake_natural',
    217: 'landfill',
    218: 'landing_deck',
    219: 'laundromat',
    220: 'lecture_room',
    221: 'library_indoor',
    222: 'library_outdoor',
    223: 'lido_deck_outdoor',
    224: 'lift_bridge',
    225: 'lighthouse',
    226: 'limousine_interior',
    227: 'living_room',
    228: 'lobby',
    229: 'lock_chamber',
    230: 'locker_room',
    231: 'mansion',
    232: 'manufactured_home',
    233: 'market_indoor',
    234: 'market_outdoor',
    235: 'marsh',
    236: 'martial_arts_gym',
    237: 'mausoleum',
    238: 'medina',
    239: 'moat_water',
    240: 'monastery_outdoor',
    241: 'mosque_indoor',
    242: 'mosque_outdoor',
    243: 'motel',
    244: 'mountain',
    245: 'mountain_snowy',
    246: 'movie_theater_indoor',
    247: 'museum_indoor',
    248: 'music_store',
    249: 'music_studio',
    250: 'nuclear_power_plant_outdoor',
    251: 'nursery',
    252: 'oast_house',
    253: 'observatory_outdoor',
    254: 'ocean',
    255: 'office',
    256: 'office_building',
    257: 'oil_refinery_outdoor',
    258: 'oilrig',
    259: 'operating_room',
    260: 'orchard',
    261: 'outhouse_outdoor',
    262: 'pagoda',
    263: 'palace',
    264: 'pantry',
    265: 'park',
    266: 'parking_garage_indoor',
    267: 'parking_garage_outdoor',
    268: 'parking_lot',
    269: 'parlor',
    270: 'pasture',
    271: 'patio',
    272: 'pavilion',
    273: 'pharmacy',
    274: 'phone_booth',
    275: 'physics_laboratory',
    276: 'picnic_area',
    277: 'pilothouse_indoor',
    278: 'planetarium_outdoor',
    279: 'playground',
    280: 'playroom',
    281: 'plaza',
    282: 'podium_indoor',
    283: 'podium_outdoor',
    284: 'pond',
    285: 'poolroom_establishment',
    286: 'poolroom_home',
    287: 'power_plant_outdoor',
    288: 'promenade_deck',
    289: 'pub_indoor',
    290: 'pulpit',
    291: 'putting_green',
    292: 'racecourse',
    293: 'raceway',
    294: 'raft',
    295: 'railroad_track',
    296: 'rainforest',
    297: 'reception',
    298: 'recreation_room',
    299: 'residential_neighborhood',
    300: 'restaurant',
    301: 'restaurant_kitchen',
    302: 'restaurant_patio',
    303: 'rice_paddy',
    304: 'riding_arena',
    305: 'river',
    306: 'rock_arch',
    307: 'rope_bridge',
    308: 'ruin',
    309: 'runway',
    310: 'sandbar',
    311: 'sandbox',
    312: 'sauna',
    313: 'schoolhouse',
    314: 'sea_cliff',
    315: 'server_room',
    316: 'shed',
    317: 'shoe_shop',
    318: 'shopfront',
    319: 'shopping_mall_indoor',
    320: 'shower',
    321: 'skatepark',
    322: 'ski_lodge',
    323: 'ski_resort',
    324: 'ski_slope',
    325: 'sky',
    326: 'skyscraper',
    327: 'slum',
    328: 'snowfield',
    329: 'squash_court',
    330: 'stable',
    331: 'stadium_baseball',
    332: 'stadium_football',
    333: 'stage_indoor',
    334: 'staircase',
    335: 'street',
    336: 'subway_interior',
    337: 'subway_station_platform',
    338: 'supermarket',
    339: 'sushi_bar',
    340: 'swamp',
    341: 'swimming_pool_indoor',
    342: 'swimming_pool_outdoor',
    343: 'synagogue_indoor',
    344: 'synagogue_outdoor',
    345: 'television_studio',
    346: 'temple_east_asia',
    347: 'temple_south_asia',
    348: 'tennis_court_indoor',
    349: 'tennis_court_outdoor',
    350: 'tent_outdoor',
    351: 'theater_indoor_procenium',
    352: 'theater_indoor_seats',
    353: 'thriftshop',
    354: 'throne_room',
    355: 'ticket_booth',
    356: 'toll_plaza',
    357: 'topiary_garden',
    358: 'tower',
    359: 'toyshop',
    360: 'track_outdoor',
    361: 'train_railway',
    362: 'train_station_platform',
    363: 'tree_farm',
    364: 'tree_house',
    365: 'trench',
    366: 'underwater_coral_reef',
    367: 'utility_room',
    368: 'valley',
    369: 'van_interior',
    370: 'vegetable_garden',
    371: 'veranda',
    372: 'veterinarians_office',
    373: 'viaduct',
    374: 'videostore',
    375: 'village',
    376: 'vineyard',
    377: 'volcano',
    378: 'volleyball_court_indoor',
    379: 'volleyball_court_outdoor',
    380: 'waiting_room',
    381: 'warehouse_indoor',
    382: 'water_tower',
    383: 'waterfall_block',
    384: 'waterfall_fan',
    385: 'waterfall_plunge',
    386: 'watering_hole',
    387: 'wave',
    388: 'wet_bar',
    389: 'wheat_field',
    390: 'wind_farm',
    391: 'windmill',
    392: 'wine_cellar_barrel_storage',
    393: 'wine_cellar_bottle_storage',
    394: 'wrestling_ring_indoor',
    395: 'yard',
    396: 'youth_hostel'
}


SUN397_TAXONOMY = {
    "Indoor": {

    "shopping and dinner": { 'shopping and dining': ['bakery_shop', 'banquet_hall', 'bar', 'bazaar_indoor', 'bistro_indoor', 'bookstore', 'butchers_shop', 'cafeteria', 'candy_store', 'clothing_store', 'coffee_shop', 'delicatessen', 'diner_indoor', 'discotheque', 'drugstore', 'fastfood_restaurant', 'florist_shop_indoor', 'food_court', 'general_store_indoor', 'gift_shop', 'ice_cream_parlor', 'jewelry_shop', 'market_indoor', 'music_store', 'pharmacy', 'pub_indoor', 'restaurant', 'shoe_shop', 'shopping_mall_indoor', 'supermarket', 'sushi_bar', 'thriftshop', 'toyshop', 'videostore', 'wine_cellar_barrel_storage', 'wine_cellar_bottle_storage'] },

    "workplace": { 'workplace (office building, factory, lab, etc.)': ['anechoic_chamber', 'assembly_line', 'atrium_public', 'auto_factory', 'biology_laboratory', 'brewery_indoor', 'cheese_factory', 'chemistry_lab', 'chicken_coop_indoor', 'clean_room', 'computer_room', 'conference_room', 'control_room', 'corridor', 'cubicle_office', 'dentists_office', 'elevator_door', 'elevator_interior', 'elevator_shaft', 'escalator_indoor', 'factory_indoor', 'greenhouse_indoor', 'hospital_room', 'kennel_indoor', 'laundromat', 'lobby', 'office', 'operating_room', 'parking_garage_indoor', 'physics_laboratory', 'reception', 'server_room', 'stable', 'ticket_booth', 'veterinarians_office', 'waiting_room', 'warehouse_indoor'] },

    "home/hotel": { 'home or hotel': ['attic', 'basement', 'bathroom', 'bedroom', 'bow_window_indoor', 'childs_room', 'closet', 'dinette_home', 'dining_room', 'dorm_room', 'game_room', 'garage_indoor', 'home_office', 'hotel_room', 'kitchen', 'kitchenette', 'living_room', 'nursery', 'pantry', 'parlor', 'playroom', 'poolroom_home', 'recreation_room', 'restaurant_kitchen', 'shower', 'staircase', 'utility_room', 'wet_bar', 'youth_hostel'] },

    "transportation": { 'transportation (vehicle interiors, stations, etc.)': ['airplane_cabin', 'airport_terminal', 'baggage_claim', 'berth', 'bus_interior', 'car_interior_backseat', 'car_interior_frontseat', 'cockpit', 'dinette_vehicle', 'dining_car', 'engine_room', 'galley', 'hangar_indoor', 'limousine_interior', 'pilothouse_indoor', 'promenade_deck', 'subway_interior', 'subway_station_platform', 'train_station_platform', 'van_interior'] }, 

    "sport": { 'sports and leisure': ['amusement_arcade', 'badminton_court_indoor', 'ball_pit', 'ballroom', 'bowling_alley', 'boxing_ring', 'casino_indoor', 'firing_range_indoor', 'gymnasium_indoor', 'ice_skating_rink_indoor', 'jacuzzi_indoor', 'locker_room', 'martial_arts_gym', 'poolroom_establishment', 'riding_arena', 'sauna', 'squash_court', 'swimming_pool_indoor', 'tennis_court_indoor', 'volleyball_court_indoor', 'wrestling_ring_indoor'] }, 

    "cultural": { 'cultural (art, education, religion, etc.)': ['apse_indoor', 'aquarium', 'archive', 'art_gallery', 'art_school', 'art_studio', 'auditorium', 'beauty_salon', 'booth_indoor', 'burial_chamber', 'catacomb', 'cathedral_indoor', 'church_indoor', 'classroom', 'cloister_indoor', 'conference_center', 'courtroom', 'jail_indoor', 'jail_cell', 'kindergarden_classroom', 'lecture_room', 'library_indoor', 'mosque_indoor', 'movie_theater_indoor', 'museum_indoor', 'music_studio', 'podium_indoor', 'pulpit', 'stage_indoor', 'synagogue_indoor', 'television_studio', 'theater_indoor_procenium', 'theater_indoor_seats', 'throne_room'] }, 

    },

    "Outdoor Natural": {

    "water": { 'water, ice, snow': ['beach', 'canal_natural', 'coast', 'creek', 'crevasse', 'dock', 'fishpond', 'hot_spring', 'ice_floe', 'ice_shelf', 'iceberg', 'islet', 'lake_natural', 'ocean', 'pond', 'raft', 'river', 'sandbar', 'sea_cliff', 'ski_slope', 'snowfield', 'swamp', 'underwater_coral_reef', 'waterfall_block', 'waterfall_fan', 'waterfall_plunge', 'watering_hole', 'wave'] }, 

    "mountain": {'mountains, hills, desert, sky': ['badlands', 'butte', 'canyon', 'cavern_indoor', 'cliff', 'desert_sand', 'desert_vegetation', 'hill', 'mountain', 'mountain_snowy', 'rock_arch', 'sky', 'valley', 'volcano']}, 

    "forest": { 'forest, field, jungle': ['bamboo_forest', 'boardwalk', 'corn_field', 'corral', 'fairway', 'field_wild', 'forest_broadleaf', 'forest_needleleaf', 'forest_path', 'forest_road', 'golf_course', 'hayfield', 'herb_garden', 'marsh', 'orchard', 'park', 'pasture', 'rainforest', 'topiary_garden', 'tree_farm', 'wheat_field'] }, 

    "man-made elements": { 'man-made elements': ['barn', 'bayou', 'boathouse', 'cottage_garden', 'field_cultivated', 'highway', 'outhouse_outdoor', 'picnic_area', 'rope_bridge', 'tent_outdoor', 'trench', 'vegetable_garden', 'viaduct', 'wind_farm', 'yard'] }, 

    },


    "Outdoor Manmade" : {
    

    "transportation": {'transportation (roads, parking, bridges, boats, airports, etc.)': ['arrival_gate_outdoor', 'boat_deck', 'bridge', 'canal_urban', 'control_tower_outdoor', 'covered_bridge_exterior', 'hangar_outdoor', 'harbor', 'heliport', 'landing_deck', 'lift_bridge', 'lock_chamber', 'parking_lot', 'railroad_track', 'runway', 'toll_plaza', 'train_railway']}, 

    "cultural/historical": { 'cultural or historical building/place': ['abbey', 'amphitheater', 'aqueduct', 'arch', 'basilica', 'campus', 'castle', 'cathedral_outdoor', 'cemetery', 'church_outdoor', 'courthouse', 'fountain', 'kasbah', 'labyrinth_outdoor', 'library_outdoor', 'lighthouse', 'mausoleum', 'medina', 'moat_water', 'monastery_outdoor', 'mosque_outdoor', 'oast_house', 'observatory_outdoor', 'pagoda', 'palace', 'planetarium_outdoor', 'plaza', 'ruin', 'synagogue_outdoor', 'temple_east_asia', 'temple_south_asia', 'tower', 'windmill'] }, 

    "sport fields": { 'sports fields, parks, leisure spaces': ['amusement_park', 'athletic_field_outdoor', 'baseball_field', 'basketball_court_outdoor', 'batters_box', 'bullring', 'campsite', 'carrousel', 'driving_range_outdoor', 'gazebo_exterior', 'hot_tub_outdoor', 'ice_skating_rink_outdoor', 'igloo', 'lido_deck_outdoor', 'pavilion', 'playground', 'podium_outdoor', 'putting_green', 'racecourse', 'raceway', 'sandbox', 'skatepark', 'stadium_baseball', 'stadium_football', 'swimming_pool_outdoor', 'tennis_court_outdoor', 'track_outdoor', 'volleyball_court_outdoor'] }, 

    "industrial construction": { 'industrial and construction': ['construction_site', 'dam', 'electrical_substation', 'excavation', 'garbage_dump', 'industrial_area', 'landfill', 'nuclear_power_plant_outdoor', 'oil_refinery_outdoor', 'oilrig', 'power_plant_outdoor', 'water_tower'] },

    "house/garden/farm": { 'houses, cabins, gardens, and farms': ['balcony_exterior', 'balcony_interior', 'barndoor', 'botanical_garden', 'bow_window_outdoor', 'cabin_outdoor', 'chalet', 'chicken_coop_outdoor', 'doorway_outdoor', 'driveway', 'formal_garden', 'greenhouse_outdoor', 'house', 'hunting_lodge_outdoor', 'kennel_outdoor', 'mansion', 'manufactured_home', 'patio', 'residential_neighborhood', 'rice_paddy', 'shed', 'ski_lodge', 'ski_resort', 'tree_house', 'veranda', 'vineyard'] }, 

    "commercial building": { 'commercial buildings, shops, markets, cities, and towns': ['alley', 'apartment_building_outdoor', 'bazaar_outdoor', 'building_facade', 'courtyard', 'crosswalk', 'diner_outdoor', 'fire_escape', 'fire_station', 'gas_station', 'general_store_outdoor', 'hospital', 'hotel_outdoor', 'inn_outdoor', 'market_outdoor', 'motel', 'office_building', 'parking_garage_outdoor', 'phone_booth', 'restaurant_patio', 'schoolhouse', 'shopfront', 'skyscraper', 'slum', 'street', 'village'] }

    }

}